### ISSUE TITLE
regression Mapper with php 8.1

### ISSUE THREAD

**Issue by leancode** [f3-factory/fatfree-core#356]
To start with not sure, when this started but I just upgraded our install from php 7.3.33 to 8.1.12 and some of our code stopped working.
In this example on the db features of F3 are used nothing else.
I had to make a note on my stackoverflow answer that my accepted answer no longer works

https://stackoverflow.com/questions/34521865/easiest-way-to-retrieve-a-single-field-from-database-with-fat-free-framework

I will demonstrate by example:
```
<?php
/*
-- Table structure and test record for table
CREATE TABLE "public"."table" (
  "id" int4 NOT NULL DEFAULT nextval('table_id_seq'::regclass),
  "text" text COLLATE "pg_catalog"."default"
);
ALTER TABLE "public"."table" ADD CONSTRAINT "table_pkey" PRIMARY KEY ("id");
--
INSERT INTO "public"."table" ("id", "text") VALUES (1, 'one');
*/

require('vendor/autoload.php');

echo "Running with php ".phpversion().", F3 ". \Base::instance()->VERSION."\n";

$db=new DB\SQL('pgsql:host=10.8.80.170;dbname=test','test','test');
$table = new DB\SQL\Mapper($db, 'table');

// This works in both versions. id=1 exists and returns "one"
$text = $table->findone(['id = ?', 1])->text;
echo "'$text'\n";

// The below throws an error in php 8.1. id=2 does not exist in db table
$text = $table->findone(['id = ?', 2])->text;
echo "'$text'\n";
```

When running with php 7.3:
```
leancode@dev ~$ ./test.php
Running with php 7.3.33, F3 version 3.8.1-Release
'one'
''
leancode@dev ~$
```
When running with php 8.1:
```
leancode@dev ~$ ./test.php
Running with php 8.1.12, F3 version 3.8.1-Release
'one'
Attempt to read property "text" on bool
[test.php:25] 
[test.php:25] Base->{closure}()

===================================
ERROR 500 - Internal Server Error
Attempt to read property "text" on bool
leancode@dev ~$
```
This is kind of a big deal because a lot of code will need to be changed. 

Would be great if we could restore the functionality as it was before and keep the old code running on newer php versions.

I don't feel up to proposing a PR for this issue because there is a lot to consider and I am not familiar enough with the F3 core.

**Comment by leancode** [comment]
Proposal:
in cursor.php the findone function
```
	/**
	*	Return first record (mapper object) that matches criteria
	*	@return static|FALSE
	*	@param $filter string|array
	*	@param $options array
	*	@param $ttl int
	**/
	function findone($filter=NULL,array $options=NULL,$ttl=0) {
		if (!$options)
			$options=[];
		// Override limit
		$options['limit']=1;
		return ($data=$this->find($filter,$options,$ttl))?$data[0]:FALSE;
	}
```
what if instead of returning FALSE if nothing is found we returned $this?
This would return an empty db object and all would be fine. Or am I missing something?
So the line would become:
`		return ($data=$this->find($filter,$options,$ttl))?$data[0]:$this;
`
I actually don't understand why it was working all these years. It seems like that if there is no result in the find false would be returned and that has no changed for a long time.

But when I change the code:
```
// The below throws an error in php 8.1. id=2 does not exist in db table
$text = $table->findone(['id = ?', 2])->text;
echo "'$text'\n";

```
to 
```
// The below throws an error in php 8.1. id=2 does not exist in db table
$obj = $table->findone(['id = ?', 2]);
var_dump($obj);
$text = $obj->text;
echo "'$text'\n";

```
The $obj (on the var_dump) is clearly not FALSE but the whole empty mapper $object.
That's why it's working on php 7.3

But the code in curser.php is pretty clear and has not been changed in 8 years. It should have returned false all along. What am I missing?

Is that a php bug that was fixed making the code suddenly behave like written?

In any case, for me it seems like whatever caused the behaviour for all these years, the behaviour should stay the same as it is clearly a feature and not a bug.

Therefore I vote to return the $this instead of FALSE to maintain backwards compatibility and allow for the sweet shortcut to continue to work (return just one column with e.g. findone(...)->text).

**Comment by leancode** [comment]
Temporary fix, if anyone runs into this:
Extend the Mapper with your own Mapper class and then use that one.
```
class Mapper extends DB\SQL\Mapper {
    function findone($filter=NULL,array $options=NULL,$ttl=0) {
        return ($data=parent::findone($filter, $options, $ttl))?$data:$this;
	}
}

```

**Comment by ikkez** [comment]
Hi. The problem rather is that PHP 8. does something different in regards of error handling. Accessing FALSE as object is obviously an error. In PHP versions before 8.0 such an error was thrown as a notice. As PHP 8 evolves into a more type-safe language, this is now a warning. You can compare the behaviour right here:

https://3v4l.org/gO4no

Php8 is much more strict, so it's likely you might find other parts that needs to be fixed. the F3 core however is compatible with php 8+ so far. To solve this issue,

- you can change the error level to `error_reporting((E_ALL|E_STRICT)&~(E_NOTICE|E_USER_NOTICE|E_WARNING));`. The error will disappear, but all other warnings too, which actually will prevent the system to notify you about problems, so I don't recommend this
- you need to check the return value of `findone`.

The only way I could think of adjusting the findone return is to

```php
return ($data=parent::findone($filter, $options, $ttl))?$data:NULL;
```

With PHP8 you can then use the `?->`null-safe operator and write

```php
echo $table->findone(['id = ?', 2])?->text;
```

That's probably the way to got, but is breaking BC, so we'll consider this as a change for F3 version 4.

**Comment by leancode** [comment]
Thanks for the attentive turn around!
You point is well received.
I just tried again because I was under the impression that in php7.3 there is the whole object in the response.
This is not actually true.
I just tried again.
Don't know what I was doing earlier, that made me think that it did.
Yes, please add that to F3v4.
Thanks for your help.
Closing this.
