### ISSUE TITLE
Null-safe operator is php 8.0+ only

### ISSUE THREAD

**Issue by ptdev** [f3-factory/fatfree-core#360]
Hey,

The change [introduced here](https://github.com/f3-factory/fatfree-core/blob/e89caa654c526a7fb823decedbebaca253fdf25a/base.php#L1069) appears to be using the null-safe operator that was apparently only [introduced with php 8](https://php.watch/versions/8.0/null-safe-operator) while the documentation still states F3 minimum requirement is php5.6+

Updating a project on latest php 7.4 for example breaks with the following error

`PHP Parse error: syntax error, unexpected '->' (T_OBJECT_OPERATOR)`

Cheers 👍

**Comment by ikkez** [comment]
fixed
