### ISSUE TITLE
Error in Web->slug() when being called by Markdown->convert()

### ISSUE THREAD

**Issue by djadomi** [f3-factory/fatfree-core#363]
[PHP 8.2]

Given the code

```php
$input = '# Eleggibilità';
$slug = \Web::instance()->slug($input);
```

`$slug` is "eleggibilita" as you'd expect.

But if we're using Markdown:

```php
$html = \Markdown::instance()->convert($input);
```

the call to `Web->slug()` to make the id anchor for the heading returns a failure:

``` log
PHP Deprecated:  strtolower(): Passing null to parameter #1 ($string) of type string is deprecated in /usr/share/nginx/html/composer/vendor/bcosca/fatfree-core/web.php on line 954"
```

If `$input` is instead "# Eleggibilità." (where the "à" isn't the last character) there are no issues; `$html` is:
``` html
<h1 id="eleggibilita">Eleggibilità.</h1>
```

**Comment by ikkez** [comment]
thanks for reporting. fixed in latest commit. I'll tag a new release.
