### ISSUE TITLE
Got 403 error with set session parameter when change IP address

### ISSUE THREAD

**Issue by uncher** [f3-factory/fatfree-core#364]
Create simple script /var/www/blabla/public/blabla.php: 
```
<?php
require('../vendor/autoload.php');
$f3 = \Base::instance();
$f3->set('DEBUG', 3);
$f3->set('CACHE', './tmp/');

new Session();

$f3->set('SESSION.test',123);

$f3->route('GET /blabla.php',
    function() {
        echo 'Hello, world!';
    }
);

$f3->run();
```
If right now change IP address and update page - I got 403 error, next update - no error until change IP address

```
[/var/www/blabla/vendor/bcosca/fatfree-core/session.php:80] Base->error()
[/var/www/blabla/vendor/bcosca/fatfree-core/base.php:311] session_start()
[/var/www/blabla/vendor/bcosca/fatfree-core/base.php:441] Base->ref()
[blabla.php:9] Base->set()
Forbidden
HTTP 403 (GET /blabla.php)
```

if i comment  or delete string `$f3->set('CACHE', './tmp/');` - no error after change IP address.

**Comment by ikkez** [comment]
this is the session hijack protection. you can disable or reimplement the behaviour by the onSuspect argument for the session handler

**Comment by uncher** [comment]
Thanks all fellows , its my fault, i didn't read the docs well.
