### ISSUE TITLE
Space at the end of route in config causes method not allowed

### ISSUE THREAD

**Issue by DaliborTrampota** [f3-factory/fatfree-core#371]
This fricking bug cost me my sanity
in routes.ini (or any config with routes) suppose we have this route

`POST /admin/backup/run/@action = \controllers\api\Backup->run_action `

if there is a trailing space, it throws method not allowed. why is it not being trimmed for god's sake?

**Comment by ikkez** [comment]
thanks. Never noticed this one, as PhpStorm already trims whitespace in .ini files automatically.
fixed now.
